[rewrite_local]
^https?:\/\/buy\.itunes\.apple\.com\/verifyReceipt url script-response-body https://cdn.jsdelivr.net/gh/fmwgz8n4hr-dotcom/Qx@main/iap-verifyreceipt-qx.js
^https?:\/\/sandbox\.itunes\.apple\.com\/verifyReceipt url script-response-body https://cdn.jsdelivr.net/gh/fmwgz8n4hr-dotcom/Qx@main/iap-verifyreceipt-qx.js

[mitm]
hostname = buy.itunes.apple.com, sandbox.itunes.apple.com
