[rewrite_local]
^https?:\/\/(interface\d?|music)\.163\.com\/(e?api)\/.* url script-response-body https://cdn.jsdelivr.net/gh/QuellaMC/NeteaseUnlocker@main/js/unblock-netease.js
^https?:\/\/(interface\d?|music)\.163\.com\/(e?api)\/.* url script-request-header https://cdn.jsdelivr.net/gh/QuellaMC/NeteaseUnlocker@main/js/unblock-netease-header.js
^https?:\/\/.*\.163\.com\/api\/ad url reject-200
^https?:\/\/.*\.163\.com\/api\/v\d\/(android|ios|osx|pc)\/(upgrade|version) url reject-200
^https?:\/\/clientlog.*\.music\.163\.com\/ url reject-200

[mitm]
hostname = *.music.163.com, *.126.net
